// src/components/HomeComponent.vue
<template>
  <section class="section p-0 m-0">
    <div class="container">
      <div class="columns is-centered">
        <div class="column is-full-width has-text-centered mb-6 mt-6">
          <div class="title rubik-glitch-regular">v are money</div>
          <div class="is-size-2 has-text-yellow">
            Stand with us, be the spark,<br />
            In this revolution’s arc,<br />
            A new era is in sight,<br />
            Join the movement, claim your right.
          </div>
        </div>
      </div>
    </div>
    <img
      src="@/assets/images/v-www-img-02.png"
      alt="making bars"
      class="is-fullwidth m-0 p-0"
      style="width: 100%"
      width="100%"
    />
    <div class="container">
      <div class="columns is-centered">
        <div class="column is-full-width has-text-centered mb-3 mt-6 is-size-2 space-mono-bold">
          CA:
          <a
            href="https://basescan.org/token/0xfca463ffce3e9528253a545a3358bba848cabc48"
            target="_blank"
            class="has-text-yellow link-hover"
          >
            0xfca463ffce3e9528253a545a3358bba848cabc48
          </a>
          <font-awesome-icon
            :icon="['fas', 'copy']"
            class="copy-icon link-hover"
            :class="{ active: isActive }"
            @click="copyToClipboard"
            @mouseover="isHovered = true"
            @mouseleave="isHovered = false"
          />
          <span v-if="showTooltip" class="tooltip">Copied</span>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { faTelegram, faTwitter, faXTwitter } from '@fortawesome/free-brands-svg-icons'
import { faCopy as faCopySolid } from '@fortawesome/free-solid-svg-icons'

const showTooltip = ref(false)
const isHovered = ref(false)
const isActive = ref(false)

const copyToClipboard = () => {
  const textToCopy = '0xfca463ffce3e9528253a545a3358bba848cabc48'
  navigator.clipboard.writeText(textToCopy).then(() => {
    showTooltip.value = true
    isActive.value = true
    setTimeout(() => {
      showTooltip.value = false
      isActive.value = false
    }, 2000)
  })
}
</script>

<style scoped>
.copy-icon {
  cursor: pointer;
  margin-left: 10px;
  transition: color 0.3s ease;
}

.copy-icon.active {
  color: inherit; /* Reset to default color on click */
}

.tooltip {
  display: inline-block;
  margin-left: 10px;
  background-color: #333;
  color: #fff;
  padding: 5px;
  border-radius: 3px;
  opacity: 1;
  transition: opacity 0.5s ease-in-out;
}

.tooltip.fade-out {
  opacity: 0;
}
</style>

// src/components/Home.tsx
"use client";

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faCopy } from "@fortawesome/free-solid-svg-icons";
import React, { useState, useCallback } from "react";
import Image from "next/image";

const Home: React.FC = () => {
  const [tooltipText, setTooltipText] = useState("Click to copy");
  const [tooltipPosition, setTooltipPosition] = useState({ x: 0, y: 0 });
  const contractAddress = "0xA2b9436D567A740357ca432b35582E93191e6a2F";

  const copyToClipboard = () => {
    navigator.clipboard.writeText(contractAddress).then(() => {
      setTooltipText("Copied!");
      setTimeout(() => {
        setTooltipText("Click to copy");
      }, 2000);
    });
  };

  const handleMouseMove = useCallback((event: React.MouseEvent) => {
    setTooltipPosition({ x: event.clientX, y: event.clientY });
  }, []);

  return (
    <section
      id="home"
      className="min-h-screen flex flex-col items-center justify-center bg-black text-yellow"
    >
      <div className="w-full max-w-4xl mx-auto p-8 flex flex-col items-center">
        <div className="w-full mb-8">
          <Image
            width={1210}
            height={403}
            src="/images/content/welcome.png"
            alt="Hero Image"
            placeholder="blur"
            blurDataURL="/images/content/blurred_welcome.png"
            style={{
              width: "100%",
              height: "auto",
              maxWidth: "100%",
              maxHeight: "100%",
            }}
          />
        </div>
        <h1>v are the original</h1>
        <div className="w-full center-content m-5 p-5">
          <button
            className="copy-button"
            onClick={copyToClipboard}
            onMouseMove={handleMouseMove}
            aria-label="Copy token to clipboard"
          >
            CA {contractAddress} <FontAwesomeIcon icon={faCopy} width={24} height={24} />
            <span
              className="tooltip"
              style={{
                left: `${tooltipPosition.x}px`,
                top: `${tooltipPosition.y - 30}px`,
                transform: 'translateX(-50%)',
              }}
            >
              {tooltipText}
            </span>
          </button>
        </div>
        <hr className="w-full my-6" />
        <div className="w-full center-content">
          <p className="text-xl text-center">
            Stand with us, be the spark
            <br />
            In this revolution&apos;s arc,
            <br />
            A new era is in sight,
            <br />
            Join the movement, claim your right.
          </p>
        </div>
      </div>
    </section>
  );
};

export default Home;
